### ISSUE TITLE
GUI disappeared after switching to Fullscreen / handle changes

### ISSUE THREAD

**Issue by riipzz** [aXXo-dev/OpenGL-Hk#2]
GUI disappeared after switching to Fullscreen

**Comment by axxo1337** [comment]
Ah, indeed it is a bug. I'm not sure how to fix this, my theory is to simply check when the user changes from full-screen to windowed and back and fourth, and if so, recreate the dummy context. I supposed it is due to some changes in the swapchain or something close to that.

**Comment by axxo1337** [comment]
I'll try to make a universal solution since my hook aims at working on any OpenGL game

**Comment by axxo1337** [comment]
Alright I pushed a fix check: https://github.com/aXXo-dev/OpenGL-Hk/commit/f5365bf93785cef41a6d956374bccec06b1bcf1e

It works now when you resize though I have seen some issues with the code that don't affect gameplay.
